apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - namespace.yaml
  - pg-cluster.yaml
  - migration-job.yaml
  - pg-backup-schedule.yaml
  
patches:
  - path: deployment-patch.yaml
  

namePrefix: prod-